logging:
  level:
    root: WARN
    org.springframework: INFO
    uk.co.mulecode.sample: DEBUG

info:
  app:
    name: sample-name
    description: sample description

server:
  port: 8080
  servlet:
    context-path: /myappname

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <client_id>
            client-secret: <client_secret>
            accessTokenUri: https://www.googleapis.com/oauth2/v4/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
            clientAuthenticationScheme: form
